project_id = "feqdqyadkijpohyllfdq"

[functions.paypal]
verify_jwt = false

[functions.payu]
verify_jwt = false

[functions.api-risk-engine]
verify_jwt = false

[functions.api-email]
verify_jwt = false
