project_id = "feqdqyadkijpohyllfdq"

[functions.paypal]
verify_jwt = false

[functions.payu]
verify_jwt = false

[functions.api-risk-engine]
verify_jwt = false

[functions.api-email]
verify_jwt = false

[functions.api-health]
verify_jwt = false

[functions.api-backup]
verify_jwt = false

[functions.check-demo-health]
verify_jwt = false

[functions.ai-empathy-engine]
verify_jwt = false

[functions.ai-crisis-analyzer]
verify_jwt = false

[functions.ai-task-assistant]
verify_jwt = false

[functions.ai-performance-analyzer]
verify_jwt = false

[functions.ai-demo-assistant]
verify_jwt = false

[functions.campaign-optimizer]
verify_jwt = false

[functions.ai-seo-automation]
verify_jwt = false

[functions.ai-legal-assistant]
verify_jwt = false

[functions.ai-performance-coach]
verify_jwt = false

[functions.ai-hr-assistant]
verify_jwt = false
