apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: softwarewala-ingress
  namespace: default
  annotations:

  - host: softwarewala.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: softwarewala-frontend
            port:
              number: 80
