apiVersion: v1
kind: Service
metadata:
  name: softwarewala-service
  namespace: default
  labels:
    app: softwarewala
spec:
  type: LoadBalancer
  selector:
    app: softwarewala
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
