/**
 * VALA AI DASHBOARD - LOVABLE-CLONE UI
 * =====================================
 * Left: Chat panel with AI conversation
 * Right: Live preview panel
 * Top: Toolbar with project controls
 * LOCKED DARK THEME
 */

import { useState, useCallback, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Send, Plus, Undo2, Redo2, Share2, Eye, Code2,
  Smartphone, Monitor, Tablet, ExternalLink, RefreshCw,
  Sparkles, Bot, User, Copy, ThumbsUp, ThumbsDown,
  Loader2, ChevronDown, Settings, Zap, Globe, Rocket,
  PanelLeftClose, PanelLeftOpen, Image, Paperclip, Mic,
  MoreHorizontal, CheckCircle, Clock, X
} from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

// ===== LOCKED COLORS =====
const C = {
  bg: '#09090b',
  bgSidebar: '#0c0c0e',
  bgChat: '#09090b',
  bgPreview: '#ffffff',
  bgInput: '#18181b',
  bgInputFocus: '#1c1c1f',
  bgMessage: '#18181b',
  bgMessageAI: '#111113',
  border: '#27272a',
  borderFocus: '#3f3f46',
  accent: '#8b5cf6',
  accentHover: '#7c3aed',
  green: '#22c55e',
  text: '#fafafa',
  textMuted: '#a1a1aa',
  textDim: '#71717a',
};

interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  isStreaming?: boolean;
}

type PreviewMode = 'preview' | 'code';
type DeviceMode = 'desktop' | 'tablet' | 'mobile';

const ValaAIDashboard = () => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: '1',
      role: 'assistant',
      content: "Hi! I'm VALA AI, your AI product builder. Describe what you want to build and I'll generate it for you.\n\nYou can ask me to:\n- Create full dashboards and apps\n- Design UI components\n- Build database schemas\n- Generate API endpoints\n- Set up authentication flows\n\nWhat would you like to build today?",
      timestamp: new Date(),
    }
  ]);
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [previewMode, setPreviewMode] = useState<PreviewMode>('preview');
  const [deviceMode, setDeviceMode] = useState<DeviceMode>('desktop');
  const [previewUrl, setPreviewUrl] = useState('');
  const [showSidebar, setShowSidebar] = useState(true);
  const [currentProject, setCurrentProject] = useState('My Project');
  const [generatedCode, setGeneratedCode] = useState(`// Generated by VALA AI\n// Start by sending a prompt...\n\nimport React from 'react';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-background">\n      <h1>Your app will appear here</h1>\n    </div>\n  );\n}`);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  // Auto-scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Simulate AI response with streaming effect
  const simulateAIResponse = useCallback((userPrompt: string) => {
    const responseId = Date.now().toString();
    
    // Add empty AI message
    const aiMessage: ChatMessage = {
      id: responseId,
      role: 'assistant',
      content: '',
      timestamp: new Date(),
      isStreaming: true,
    };
    setMessages(prev => [...prev, aiMessage]);

    // Simulate streaming response
    const responses: Record<string, string> = {
      dashboard: `I'll create a modern dashboard for you. Here's what I'm building:\n\n**Components Generated:**\n- \`DashboardLayout.tsx\` - Main layout with sidebar\n- \`StatsCards.tsx\` - KPI metric cards\n- \`RevenueChart.tsx\` - Revenue trend chart\n- \`RecentActivity.tsx\` - Activity feed\n- \`UserTable.tsx\` - User management table\n\n**Database Tables:**\n- \`users\` - User accounts\n- \`analytics\` - Usage metrics\n- \`transactions\` - Revenue data\n\n**API Endpoints:**\n- \`GET /api/stats\` - Dashboard metrics\n- \`GET /api/users\` - User list\n- \`POST /api/users\` - Create user\n\n✅ All components generated and connected. You can see the preview on the right.`,
      auth: `Setting up authentication for you:\n\n**Auth System Generated:**\n- \`LoginPage.tsx\` - Email/password login\n- \`SignupPage.tsx\` - User registration\n- \`ForgotPassword.tsx\` - Password recovery\n- \`AuthProvider.tsx\` - Auth context\n- \`ProtectedRoute.tsx\` - Route guard\n\n**Database:**\n- Profiles table with RLS policies\n- Session management\n\n✅ Authentication system is ready. Users can now sign up and log in.`,
      default: `I'll work on that for you. Here's my plan:\n\n**Analysis:**\nI've analyzed your requirements and identified the key components needed.\n\n**Steps:**\n1. ✅ Requirement Analysis - Complete\n2. ✅ Component Architecture - Complete\n3. ✅ UI Generation - Complete\n4. ✅ Logic Implementation - Complete\n5. ✅ Integration - Complete\n\n**Generated:**\n- 4 React components\n- 2 database tables\n- 3 API endpoints\n- Full styling with Tailwind CSS\n\n✅ Generation complete! Check the preview on the right panel.`,
    };

    const promptLower = userPrompt.toLowerCase();
    let fullResponse = responses.default;
    if (promptLower.includes('dashboard') || promptLower.includes('admin')) fullResponse = responses.dashboard;
    else if (promptLower.includes('auth') || promptLower.includes('login') || promptLower.includes('signup')) fullResponse = responses.auth;

    // Stream character by character
    let charIndex = 0;
    const streamInterval = setInterval(() => {
      charIndex += Math.floor(Math.random() * 3) + 2;
      if (charIndex >= fullResponse.length) {
        charIndex = fullResponse.length;
        clearInterval(streamInterval);
        setMessages(prev => prev.map(m =>
          m.id === responseId ? { ...m, content: fullResponse, isStreaming: false } : m
        ));
        setIsGenerating(false);
        
        // Update generated code
        setGeneratedCode(`// Generated by VALA AI
// Prompt: "${userPrompt}"

import React from 'react';

export default function GeneratedApp() {
  return (
    <div className="min-h-screen bg-slate-50 p-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold text-slate-900 mb-8">
          ${userPrompt.slice(0, 50)}
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white rounded-xl p-6 shadow-sm border">
            <h3 className="font-semibold text-slate-700">Component 1</h3>
            <p className="text-2xl font-bold mt-2">1,234</p>
          </div>
          <div className="bg-white rounded-xl p-6 shadow-sm border">
            <h3 className="font-semibold text-slate-700">Component 2</h3>
            <p className="text-2xl font-bold mt-2">5,678</p>
          </div>
          <div className="bg-white rounded-xl p-6 shadow-sm border">
            <h3 className="font-semibold text-slate-700">Component 3</h3>
            <p className="text-2xl font-bold mt-2">9,012</p>
          </div>
        </div>
      </div>
    </div>
  );
}`);
      } else {
        setMessages(prev => prev.map(m =>
          m.id === responseId ? { ...m, content: fullResponse.slice(0, charIndex) } : m
        ));
      }
    }, 15);
  }, []);

  const handleSend = useCallback(() => {
    if (!input.trim() || isGenerating) return;

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsGenerating(true);

    // Simulate brief delay then AI response
    setTimeout(() => simulateAIResponse(userMessage.content), 500);
  }, [input, isGenerating, simulateAIResponse]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const getDeviceWidth = () => {
    switch (deviceMode) {
      case 'mobile': return '375px';
      case 'tablet': return '768px';
      default: return '100%';
    }
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden" style={{ background: C.bg, color: C.text }}>
      {/* Top Toolbar */}
      <div
        className="flex items-center justify-between px-4 h-12 shrink-0"
        style={{ borderBottom: `1px solid ${C.border}`, background: C.bgSidebar }}
      >
        {/* Left: Project info */}
        <div className="flex items-center gap-3">
          <button
            onClick={() => setShowSidebar(!showSidebar)}
            className="p-1.5 rounded-md hover:bg-white/5 transition-colors"
            style={{ color: C.textMuted }}
          >
            {showSidebar ? <PanelLeftClose className="w-4 h-4" /> : <PanelLeftOpen className="w-4 h-4" />}
          </button>
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md flex items-center justify-center text-xs font-bold" style={{ background: C.accent, color: '#fff' }}>V</div>
            <span className="text-sm font-medium" style={{ color: C.text }}>{currentProject}</span>
            <ChevronDown className="w-3.5 h-3.5" style={{ color: C.textMuted }} />
          </div>
        </div>

        {/* Center: Undo/Redo */}
        <div className="flex items-center gap-1">
          <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
            <Undo2 className="w-4 h-4" />
          </button>
          <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
            <Redo2 className="w-4 h-4" />
          </button>
        </div>

        {/* Right: Actions */}
        <div className="flex items-center gap-2">
          <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium hover:bg-white/5 transition-colors" style={{ color: C.textMuted, border: `1px solid ${C.border}` }}>
            <Share2 className="w-3.5 h-3.5" /> Share
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-colors" style={{ background: C.accent, color: '#fff' }}>
            <Rocket className="w-3.5 h-3.5" /> Publish
          </button>
        </div>
      </div>

      {/* Main Content: Chat + Preview */}
      <div className="flex-1 flex overflow-hidden">
        {/* LEFT: Chat Panel */}
        <div
          className={cn("flex flex-col transition-all duration-200", showSidebar ? "w-[420px]" : "w-0 overflow-hidden")}
          style={{ borderRight: `1px solid ${C.border}`, background: C.bgChat }}
        >
          {/* Chat Messages */}
          <ScrollArea className="flex-1 px-4 py-4">
            <div className="space-y-6">
              {messages.map((msg) => (
                <div key={msg.id} className="group">
                  {/* Sender Label */}
                  <div className="flex items-center gap-2 mb-2">
                    {msg.role === 'assistant' ? (
                      <>
                        <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #8b5cf6, #06b6d4)' }}>
                          <Sparkles className="w-3 h-3 text-white" />
                        </div>
                        <span className="text-xs font-medium" style={{ color: C.textMuted }}>VALA AI</span>
                      </>
                    ) : (
                      <>
                        <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ background: '#3f3f46' }}>
                          <User className="w-3 h-3 text-white" />
                        </div>
                        <span className="text-xs font-medium" style={{ color: C.textMuted }}>You</span>
                      </>
                    )}
                  </div>

                  {/* Message Content */}
                  <div className="pl-8">
                    <div
                      className="text-sm leading-relaxed whitespace-pre-wrap"
                      style={{ color: C.text }}
                    >
                      {msg.content}
                      {msg.isStreaming && (
                        <span className="inline-block w-0.5 h-4 ml-0.5 animate-pulse" style={{ background: C.accent }} />
                      )}
                    </div>

                    {/* Action buttons for AI messages (not streaming) */}
                    {msg.role === 'assistant' && !msg.isStreaming && (
                      <div className="flex items-center gap-1 mt-3 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button className="p-1 rounded hover:bg-white/5" style={{ color: C.textDim }}>
                          <Copy className="w-3.5 h-3.5" />
                        </button>
                        <button className="p-1 rounded hover:bg-white/5" style={{ color: C.textDim }}>
                          <ThumbsUp className="w-3.5 h-3.5" />
                        </button>
                        <button className="p-1 rounded hover:bg-white/5" style={{ color: C.textDim }}>
                          <ThumbsDown className="w-3.5 h-3.5" />
                        </button>
                        <button className="p-1 rounded hover:bg-white/5" style={{ color: C.textDim }}>
                          <RefreshCw className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              ))}
              <div ref={messagesEndRef} />
            </div>
          </ScrollArea>

          {/* Chat Input */}
          <div className="p-4 shrink-0" style={{ borderTop: `1px solid ${C.border}` }}>
            {isGenerating && (
              <div className="flex items-center gap-2 mb-3 px-1">
                <Loader2 className="w-3.5 h-3.5 animate-spin" style={{ color: C.accent }} />
                <span className="text-xs" style={{ color: C.textMuted }}>VALA AI is generating...</span>
                <button
                  onClick={() => setIsGenerating(false)}
                  className="ml-auto text-xs px-2 py-0.5 rounded hover:bg-white/5"
                  style={{ color: C.textDim, border: `1px solid ${C.border}` }}
                >
                  Stop
                </button>
              </div>
            )}
            <div
              className="rounded-xl overflow-hidden"
              style={{ background: C.bgInput, border: `1px solid ${C.border}` }}
            >
              <textarea
                ref={inputRef}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="Describe what you want to build..."
                rows={3}
                className="w-full px-4 py-3 text-sm resize-none outline-none"
                style={{ background: 'transparent', color: C.text }}
              />
              <div className="flex items-center justify-between px-3 py-2" style={{ borderTop: `1px solid ${C.border}` }}>
                <div className="flex items-center gap-1">
                  <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
                    <Paperclip className="w-4 h-4" />
                  </button>
                  <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
                    <Image className="w-4 h-4" />
                  </button>
                </div>
                <button
                  onClick={handleSend}
                  disabled={!input.trim() || isGenerating}
                  className="p-2 rounded-lg transition-colors disabled:opacity-30"
                  style={{ background: input.trim() ? C.accent : 'transparent', color: '#fff' }}
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </div>
            <p className="text-center mt-2 text-[10px]" style={{ color: C.textDim }}>
              VALA AI can make mistakes. Review generated output carefully.
            </p>
          </div>
        </div>

        {/* RIGHT: Preview Panel */}
        <div className="flex-1 flex flex-col overflow-hidden" style={{ background: '#1a1a1e' }}>
          {/* Preview Toolbar */}
          <div
            className="flex items-center justify-between px-4 h-10 shrink-0"
            style={{ borderBottom: `1px solid ${C.border}`, background: C.bgSidebar }}
          >
            <div className="flex items-center gap-1">
              <button
                onClick={() => setPreviewMode('preview')}
                className={cn("flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-colors")}
                style={{
                  background: previewMode === 'preview' ? 'rgba(255,255,255,0.08)' : 'transparent',
                  color: previewMode === 'preview' ? C.text : C.textDim,
                }}
              >
                <Eye className="w-3.5 h-3.5" /> Preview
              </button>
              <button
                onClick={() => setPreviewMode('code')}
                className={cn("flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium transition-colors")}
                style={{
                  background: previewMode === 'code' ? 'rgba(255,255,255,0.08)' : 'transparent',
                  color: previewMode === 'code' ? C.text : C.textDim,
                }}
              >
                <Code2 className="w-3.5 h-3.5" /> Code
              </button>
            </div>

            {/* Device Mode Switcher */}
            <div className="flex items-center gap-1">
              {[
                { mode: 'desktop' as DeviceMode, icon: Monitor },
                { mode: 'tablet' as DeviceMode, icon: Tablet },
                { mode: 'mobile' as DeviceMode, icon: Smartphone },
              ].map(({ mode, icon: Icon }) => (
                <button
                  key={mode}
                  onClick={() => setDeviceMode(mode)}
                  className="p-1.5 rounded-md transition-colors"
                  style={{
                    background: deviceMode === mode ? 'rgba(255,255,255,0.08)' : 'transparent',
                    color: deviceMode === mode ? C.text : C.textDim,
                  }}
                >
                  <Icon className="w-4 h-4" />
                </button>
              ))}
            </div>

            <div className="flex items-center gap-1">
              <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
                <RefreshCw className="w-3.5 h-3.5" />
              </button>
              <button className="p-1.5 rounded-md hover:bg-white/5 transition-colors" style={{ color: C.textDim }}>
                <ExternalLink className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>

          {/* Preview Content */}
          <div className="flex-1 flex items-center justify-center p-4 overflow-auto">
            {previewMode === 'preview' ? (
              <div
                className="h-full rounded-lg overflow-hidden shadow-2xl transition-all duration-300"
                style={{
                  width: getDeviceWidth(),
                  maxWidth: '100%',
                  background: '#ffffff',
                  border: `1px solid ${C.border}`,
                }}
              >
                {/* Simulated Browser Chrome */}
                <div className="flex items-center gap-2 px-3 py-2" style={{ background: '#f5f5f5', borderBottom: '1px solid #e5e5e5' }}>
                  <div className="flex gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                    <div className="w-2.5 h-2.5 rounded-full bg-green-400" />
                  </div>
                  <div className="flex-1 mx-8">
                    <div className="flex items-center gap-1.5 px-3 py-1 rounded-md text-xs" style={{ background: '#fff', border: '1px solid #e5e5e5', color: '#666' }}>
                      <Globe className="w-3 h-3" />
                      <span>localhost:5173</span>
                    </div>
                  </div>
                </div>
                {/* Simulated App Content */}
                <div className="p-8" style={{ minHeight: '400px' }}>
                  {messages.length <= 1 ? (
                    <div className="flex flex-col items-center justify-center h-80 text-center">
                      <div className="w-16 h-16 rounded-2xl flex items-center justify-center mb-4" style={{ background: 'linear-gradient(135deg, #8b5cf6, #06b6d4)' }}>
                        <Sparkles className="w-8 h-8 text-white" />
                      </div>
                      <h2 className="text-xl font-bold text-slate-900 mb-2">Your app preview</h2>
                      <p className="text-sm text-slate-500 max-w-xs">
                        Send a prompt in the chat to generate your application. The preview will appear here.
                      </p>
                    </div>
                  ) : (
                    <div>
                      <h1 className="text-2xl font-bold text-slate-900 mb-6">Generated Application</h1>
                      <div className="grid grid-cols-3 gap-4 mb-6">
                        {['Users', 'Revenue', 'Active'].map((label, i) => (
                          <div key={label} className="bg-white rounded-xl p-5 shadow-sm" style={{ border: '1px solid #e5e7eb' }}>
                            <p className="text-xs font-medium text-slate-500 mb-1">{label}</p>
                            <p className="text-2xl font-bold text-slate-900">{(i + 1) * 1234}</p>
                            <p className="text-xs text-green-600 mt-1">↑ {(i + 1) * 3.2}%</p>
                          </div>
                        ))}
                      </div>
                      <div className="bg-white rounded-xl p-5 shadow-sm" style={{ border: '1px solid #e5e7eb' }}>
                        <h3 className="text-sm font-semibold text-slate-900 mb-4">Recent Activity</h3>
                        {['User signed up', 'Order placed', 'Payment received', 'Report generated'].map((item, i) => (
                          <div key={i} className="flex items-center justify-between py-2" style={{ borderBottom: i < 3 ? '1px solid #f3f4f6' : 'none' }}>
                            <span className="text-sm text-slate-700">{item}</span>
                            <span className="text-xs text-slate-400">{i + 1}m ago</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              /* Code View */
              <div className="w-full h-full rounded-lg overflow-hidden" style={{ background: '#0d1117', border: `1px solid ${C.border}` }}>
                <div className="flex items-center justify-between px-4 py-2" style={{ borderBottom: '1px solid #21262d' }}>
                  <span className="text-xs font-medium" style={{ color: '#8b949e' }}>App.tsx</span>
                  <button
                    onClick={() => { navigator.clipboard.writeText(generatedCode); toast.success('Code copied!'); }}
                    className="p-1 rounded hover:bg-white/5"
                    style={{ color: '#8b949e' }}
                  >
                    <Copy className="w-3.5 h-3.5" />
                  </button>
                </div>
                <ScrollArea className="h-full">
                  <pre className="p-4 text-sm leading-6 font-mono" style={{ color: '#e6edf3' }}>
                    <code>{generatedCode}</code>
                  </pre>
                </ScrollArea>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ValaAIDashboard;
