// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Detect session from URL hash on OAuth redirects only
    detectSessionInUrl: true,
    // Use PKCE flow for enhanced security (prevents auth code interception)
    flowType: 'pkce',
  },
  global: {
    headers: {
      // Identify the client application to the API layer
      'X-Client-Info': 'softwarevala-web',
    },
  },
});